/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipeIdRouteImport } from './routes/recipe.$id'
import { Route as DashboardRecipesRouteImport } from './routes/_dashboard.recipes'
import { Route as DashboardProgressRouteImport } from './routes/_dashboard.progress'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard.profile'
import { Route as DashboardMealPlannerRouteImport } from './routes/_dashboard.meal-planner'
import { Route as DashboardGroceryRouteImport } from './routes/_dashboard.grocery'
import { Route as DashboardFoodDatabaseRouteImport } from './routes/_dashboard.food-database'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard.dashboard'
import { Route as DashboardRecipesIdRouteImport } from './routes/_dashboard.recipes.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeIdRoute = RecipeIdRouteImport.update({
  id: '/recipe/$id',
  path: '/recipe/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRecipesRoute = DashboardRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProgressRoute = DashboardProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMealPlannerRoute = DashboardMealPlannerRouteImport.update({
  id: '/meal-planner',
  path: '/meal-planner',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGroceryRoute = DashboardGroceryRouteImport.update({
  id: '/grocery',
  path: '/grocery',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFoodDatabaseRoute = DashboardFoodDatabaseRouteImport.update({
  id: '/food-database',
  path: '/food-database',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecipesIdRoute = DashboardRecipesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardRecipesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/food-database': typeof DashboardFoodDatabaseRoute
  '/grocery': typeof DashboardGroceryRoute
  '/meal-planner': typeof DashboardMealPlannerRoute
  '/profile': typeof DashboardProfileRoute
  '/progress': typeof DashboardProgressRoute
  '/recipes': typeof DashboardRecipesRouteWithChildren
  '/recipe/$id': typeof RecipeIdRoute
  '/recipes/$id': typeof DashboardRecipesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/food-database': typeof DashboardFoodDatabaseRoute
  '/grocery': typeof DashboardGroceryRoute
  '/meal-planner': typeof DashboardMealPlannerRoute
  '/profile': typeof DashboardProfileRoute
  '/progress': typeof DashboardProgressRoute
  '/recipes': typeof DashboardRecipesRouteWithChildren
  '/recipe/$id': typeof RecipeIdRoute
  '/recipes/$id': typeof DashboardRecipesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/food-database': typeof DashboardFoodDatabaseRoute
  '/_dashboard/grocery': typeof DashboardGroceryRoute
  '/_dashboard/meal-planner': typeof DashboardMealPlannerRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/progress': typeof DashboardProgressRoute
  '/_dashboard/recipes': typeof DashboardRecipesRouteWithChildren
  '/recipe/$id': typeof RecipeIdRoute
  '/_dashboard/recipes/$id': typeof DashboardRecipesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/dashboard'
    | '/food-database'
    | '/grocery'
    | '/meal-planner'
    | '/profile'
    | '/progress'
    | '/recipes'
    | '/recipe/$id'
    | '/recipes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/dashboard'
    | '/food-database'
    | '/grocery'
    | '/meal-planner'
    | '/profile'
    | '/progress'
    | '/recipes'
    | '/recipe/$id'
    | '/recipes/$id'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_dashboard/dashboard'
    | '/_dashboard/food-database'
    | '/_dashboard/grocery'
    | '/_dashboard/meal-planner'
    | '/_dashboard/profile'
    | '/_dashboard/progress'
    | '/_dashboard/recipes'
    | '/recipe/$id'
    | '/_dashboard/recipes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  RecipeIdRoute: typeof RecipeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/$id': {
      id: '/recipe/$id'
      path: '/recipe/$id'
      fullPath: '/recipe/$id'
      preLoaderRoute: typeof RecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/recipes': {
      id: '/_dashboard/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof DashboardRecipesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/progress': {
      id: '/_dashboard/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof DashboardProgressRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/meal-planner': {
      id: '/_dashboard/meal-planner'
      path: '/meal-planner'
      fullPath: '/meal-planner'
      preLoaderRoute: typeof DashboardMealPlannerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/grocery': {
      id: '/_dashboard/grocery'
      path: '/grocery'
      fullPath: '/grocery'
      preLoaderRoute: typeof DashboardGroceryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/food-database': {
      id: '/_dashboard/food-database'
      path: '/food-database'
      fullPath: '/food-database'
      preLoaderRoute: typeof DashboardFoodDatabaseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/recipes/$id': {
      id: '/_dashboard/recipes/$id'
      path: '/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof DashboardRecipesIdRouteImport
      parentRoute: typeof DashboardRecipesRoute
    }
  }
}

interface DashboardRecipesRouteChildren {
  DashboardRecipesIdRoute: typeof DashboardRecipesIdRoute
}

const DashboardRecipesRouteChildren: DashboardRecipesRouteChildren = {
  DashboardRecipesIdRoute: DashboardRecipesIdRoute,
}

const DashboardRecipesRouteWithChildren =
  DashboardRecipesRoute._addFileChildren(DashboardRecipesRouteChildren)

interface DashboardRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardFoodDatabaseRoute: typeof DashboardFoodDatabaseRoute
  DashboardGroceryRoute: typeof DashboardGroceryRoute
  DashboardMealPlannerRoute: typeof DashboardMealPlannerRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardProgressRoute: typeof DashboardProgressRoute
  DashboardRecipesRoute: typeof DashboardRecipesRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardFoodDatabaseRoute: DashboardFoodDatabaseRoute,
  DashboardGroceryRoute: DashboardGroceryRoute,
  DashboardMealPlannerRoute: DashboardMealPlannerRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardProgressRoute: DashboardProgressRoute,
  DashboardRecipesRoute: DashboardRecipesRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  RecipeIdRoute: RecipeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
